#############################################################################
# Makefile for building: simpleSynth
# Generated by qmake (2.01a) (Qt 4.5.2) on: Wed Jan 13 18:48:19 2010
# Project:  simpleSynth.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile simpleSynth.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -ljack -lrt -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gui.cpp \
		jack.cpp \
		synth.cpp \
		main.cpp \
		envelope.cpp moc_synth.cpp \
		moc_adsr.cpp \
		moc_qknob.cpp
OBJECTS       = gui.o \
		jack.o \
		synth.o \
		main.o \
		envelope.o \
		moc_synth.o \
		moc_adsr.o \
		moc_qknob.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		simpleSynth.pro
QMAKE_TARGET  = simpleSynth
DESTDIR       = 
TARGET        = simpleSynth

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simpleSynth.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile simpleSynth.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile simpleSynth.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/simpleSynth1.0.0 || $(MKDIR) .tmp/simpleSynth1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simpleSynth1.0.0/ && $(COPY_FILE) --parents gui.hpp jack.hpp synth.hpp adsr.hpp envelope.hpp note.hpp qknob.hpp .tmp/simpleSynth1.0.0/ && $(COPY_FILE) --parents gui.cpp jack.cpp synth.cpp main.cpp envelope.cpp .tmp/simpleSynth1.0.0/ && (cd `dirname .tmp/simpleSynth1.0.0` && $(TAR) simpleSynth1.0.0.tar simpleSynth1.0.0 && $(COMPRESS) simpleSynth1.0.0.tar) && $(MOVE) `dirname .tmp/simpleSynth1.0.0`/simpleSynth1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simpleSynth1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_synth.cpp moc_adsr.cpp moc_qknob.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_synth.cpp moc_adsr.cpp moc_qknob.cpp
moc_synth.cpp: jack.hpp \
		note.hpp \
		adsr.hpp \
		envelope.hpp \
		synth.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) synth.hpp -o moc_synth.cpp

moc_adsr.cpp: adsr.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) adsr.hpp -o moc_adsr.cpp

moc_qknob.cpp: qknob.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qknob.hpp -o moc_qknob.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

gui.o: gui.cpp gui.hpp \
		synth.hpp \
		jack.hpp \
		note.hpp \
		adsr.hpp \
		envelope.hpp \
		qknob.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o gui.cpp

jack.o: jack.cpp jack.hpp \
		synth.hpp \
		note.hpp \
		adsr.hpp \
		envelope.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jack.o jack.cpp

synth.o: synth.cpp synth.hpp \
		jack.hpp \
		note.hpp \
		adsr.hpp \
		envelope.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o synth.o synth.cpp

main.o: main.cpp gui.hpp \
		jack.hpp \
		synth.hpp \
		note.hpp \
		adsr.hpp \
		envelope.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

envelope.o: envelope.cpp jack.hpp \
		adsr.hpp \
		envelope.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o envelope.o envelope.cpp

moc_synth.o: moc_synth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_synth.o moc_synth.cpp

moc_adsr.o: moc_adsr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adsr.o moc_adsr.cpp

moc_qknob.o: moc_qknob.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qknob.o moc_qknob.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

